name: Deploy and Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Atualizando repositório
        uses: actions/checkout@v2

      - name: Criando o ambiente
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Instalando dependências
        run: npm install

      - name: Gerando o projeto
        run: npm run build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE
